-- Run this in the Supabase SQL editor for the project that backs this app.
-- The frontend uploads directly with the anon key, so Storage and the
-- GPX route metadata tables need anon policies.

insert into storage.buckets (id, name, public)
values ('route-gpx-files', 'route-gpx-files', true)
on conflict (id) do update
set public = excluded.public;

create table if not exists public.gpx_route_catalog (
  id bigint generated by default as identity primary key,
  title text not null,
  file_name text not null,
  file_size bigint not null,
  gpx_url text not null,
  storage_path text not null unique,
  distance double precision not null,
  elevation_gain double precision not null,
  elevation_loss double precision not null,
  max_elevation double precision not null,
  point_count integer not null,
  start_lat double precision,
  start_lng double precision,
  end_lat double precision,
  end_lng double precision,
  due_date date,
  region_sido text not null,
  region_city text,
  url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.gpx_route_catalog
add column if not exists title text,
add column if not exists file_name text,
add column if not exists file_size bigint,
add column if not exists gpx_url text,
add column if not exists storage_path text,
add column if not exists distance double precision,
add column if not exists elevation_gain double precision,
add column if not exists elevation_loss double precision,
add column if not exists max_elevation double precision,
add column if not exists point_count integer,
add column if not exists start_lat double precision,
add column if not exists start_lng double precision,
add column if not exists end_lat double precision,
add column if not exists end_lng double precision,
add column if not exists due_date date,
add column if not exists region_sido text,
add column if not exists region_city text,
add column if not exists url text,
add column if not exists created_at timestamptz default now(),
add column if not exists updated_at timestamptz;

alter table public.gpx_route_catalog
alter column distance type double precision using distance::double precision,
alter column elevation_gain type double precision using elevation_gain::double precision,
alter column elevation_loss type double precision using elevation_loss::double precision,
alter column max_elevation type double precision using max_elevation::double precision,
alter column start_lat type double precision using start_lat::double precision,
alter column start_lng type double precision using start_lng::double precision,
alter column end_lat type double precision using end_lat::double precision,
alter column end_lng type double precision using end_lng::double precision;

alter table public.gpx_route_catalog
alter column created_at set default now();

alter table public.gpx_route_catalog
alter column due_date drop not null;

update public.gpx_route_catalog
set region_sido = '미분류'
where region_sido is null or region_sido = '';

alter table public.gpx_route_catalog
alter column region_sido set not null;

with null_created_rows as (
  select
    id,
    row_number() over (order by id desc) as row_number
  from public.gpx_route_catalog
  where created_at is null
)
update public.gpx_route_catalog
set created_at =
  now() - ((null_created_rows.row_number - 1) * interval '1 second')
from null_created_rows
where public.gpx_route_catalog.id = null_created_rows.id;

create sequence if not exists public.gpx_route_catalog_id_seq;

select setval(
  'public.gpx_route_catalog_id_seq',
  greatest(
    coalesce((select max(id) from public.gpx_route_catalog), 0),
    1
  ),
  true
);

alter sequence public.gpx_route_catalog_id_seq
owned by public.gpx_route_catalog.id;

alter table public.gpx_route_catalog
alter column id set default nextval('public.gpx_route_catalog_id_seq');

create unique index if not exists gpx_route_catalog_storage_path_key
on public.gpx_route_catalog (storage_path);

create table if not exists public.gpx_route_checkpoints (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.gpx_route_catalog(id) on delete cascade,
  sequence integer not null,
  distance_km double precision not null,
  created_at timestamptz not null default now(),
  unique (route_id, sequence)
);

alter table public.gpx_route_checkpoints
add column if not exists route_id bigint,
add column if not exists sequence integer,
add column if not exists distance_km double precision,
add column if not exists created_at timestamptz default now();

alter table public.gpx_route_checkpoints
alter column distance_km type double precision using distance_km::double precision,
alter column created_at set default now();

create sequence if not exists public.gpx_route_checkpoints_id_seq;

select setval(
  'public.gpx_route_checkpoints_id_seq',
  greatest(
    coalesce((select max(id) from public.gpx_route_checkpoints), 0),
    1
  ),
  true
);

alter sequence public.gpx_route_checkpoints_id_seq
owned by public.gpx_route_checkpoints.id;

alter table public.gpx_route_checkpoints
alter column id set default nextval('public.gpx_route_checkpoints_id_seq');

create index if not exists gpx_route_checkpoints_route_id_idx
on public.gpx_route_checkpoints (route_id);

alter table public.gpx_route_catalog enable row level security;
alter table public.gpx_route_checkpoints enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on public.gpx_route_catalog to anon, authenticated;
grant select, insert on public.gpx_route_checkpoints to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists "Allow public GPX metadata reads" on public.gpx_route_catalog;

create policy "Allow public GPX metadata reads"
on public.gpx_route_catalog
for select
to public
using (true);

drop policy if exists "Allow public GPX metadata inserts" on public.gpx_route_catalog;

create policy "Allow public GPX metadata inserts"
on public.gpx_route_catalog
for insert
to public
with check (true);

drop policy if exists "Allow public GPX checkpoint reads" on public.gpx_route_checkpoints;

create policy "Allow public GPX checkpoint reads"
on public.gpx_route_checkpoints
for select
to public
using (true);

drop policy if exists "Allow public GPX checkpoint inserts" on public.gpx_route_checkpoints;

create policy "Allow public GPX checkpoint inserts"
on public.gpx_route_checkpoints
for insert
to public
with check (true);

drop policy if exists "Allow public GPX uploads" on storage.objects;

create policy "Allow public GPX uploads"
on storage.objects
for insert
to public
with check (
  bucket_id = 'route-gpx-files'
  and lower(storage.extension(name)) = 'gpx'
);

-- Optional: allow public reads from the same bucket if GPX files will be listed
-- or downloaded directly from the browser later.
drop policy if exists "Allow public GPX reads" on storage.objects;

create policy "Allow public GPX reads"
on storage.objects
for select
to public
using (bucket_id = 'route-gpx-files');

notify pgrst, 'reload schema';
